/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package regex;

import org.junit.Test;
import static org.junit.Assert.*;
import regex.compiler.Parser;
import regex.exceptions.InvalidRegexException;
import regex.exceptions.InvalidRegexOperatorException;

public class RegexCompilerTests {
    @Test public void addConcatenationSymbolTest1() {
        assertEquals("a#b*#(c#d#d)",Parser.addConcatenationSymbol("ab*(cdd)"));
    }
    @Test public void addConcatenationSymbolTest2() {
        assertEquals("b*",Parser.addConcatenationSymbol("b*"));
    }
    @Test public void addConcatenationSymbolTest3() {
        assertEquals("a|b",Parser.addConcatenationSymbol("a|b"));
    }
    @Test public void addConcatenationSymbolTest4() {
        assertEquals("a#b",Parser.addConcatenationSymbol("ab"));
    }
    @Test public void addConcatenationSymbolTest5() {
        assertEquals("a#b#c#a#b#c",Parser.addConcatenationSymbol("abcabc"));
    }
    @Test public void addConcatenationSymbolTest6() {
        assertEquals("a#b*",Parser.addConcatenationSymbol("ab*"));
    }
    @Test public void addConcatenationSymbolTest7() {
        assertEquals("",Parser.addConcatenationSymbol(""));
    }
    @Test public void addConcatenationSymbolTest8() {
        assertEquals("a#a#(b#b)+|b#b#(a#a)+",Parser.addConcatenationSymbol("aa(bb)+|bb(aa)+"));
    }
    @Test public void regexToPostFixTest1() throws InvalidRegexOperatorException, InvalidRegexException {
        assertEquals("aa#bb#+#bb#aa#+#|",Parser.regexToPostFix(Parser.addConcatenationSymbol("aa(bb)+|bb(aa)+")));
    }
    @Test public void regexToPostFixTest2() throws InvalidRegexOperatorException, InvalidRegexException {
        assertEquals("",Parser.regexToPostFix(Parser.addConcatenationSymbol("")));
    }
    @Test public void regexToPostFixTest3() throws InvalidRegexOperatorException, InvalidRegexException {
        assertEquals("ab#",Parser.regexToPostFix(Parser.addConcatenationSymbol("ab")));
    }
    @Test public void regexToPostFixTest4() throws InvalidRegexOperatorException, InvalidRegexException {
        assertEquals("a",Parser.regexToPostFix(Parser.addConcatenationSymbol("a")));
    }
    @Test public void regexToPostFixTest5() throws InvalidRegexOperatorException, InvalidRegexException {
        assertEquals("a*b#",Parser.regexToPostFix(Parser.addConcatenationSymbol("a*b")));
    }
    @Test public void regexToPostFixTest6() throws InvalidRegexOperatorException, InvalidRegexException {
        assertEquals("abb#+#a#",Parser.regexToPostFix(Parser.addConcatenationSymbol("a(bb)+a")));
    }
    @Test public void regexToPostFixTest7() throws InvalidRegexOperatorException, InvalidRegexException {
        assertEquals("ab#?cd#?|",Parser.regexToPostFix(Parser.addConcatenationSymbol("(ab)?|(cd)?")));
    }
}
